# Generated by Django 5.1.15 on 2026-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
